services:
  - type: web
    name: datagpt
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python datagpt.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
        
      - key: FLASK_ENV
        value: production

      - key: PORT
        value: 5000

      - key: MAX_CONTENT_LENGTH
        value: "16777216"

      - key: LOG_LEVEL
        value: INFO